<a href="https://colab.research.google.com/github/qwiksilva/cs224w-github-rec/blob/master/BigQueryGithub.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

In [0]:
%load_ext google.colab.data_table
# %unload_ext google.colab.data_table

In [0]:
# Fetch the largest 20 projects by the number of prs they have.
%%bigquery --project cs224w-257119 df
SELECT prs.num_prs, prs.base_repo_id, projects.name, projects.deleted
FROM (
  SELECT COUNT(base_repo_id) as num_prs, base_repo_id
  FROM `ghtorrent-bq.ght_2018_04_01.pull_requests`
  GROUP BY base_repo_id
) prs
INNER JOIN `ghtorrent-bq.ght_2018_04_01.projects` projects ON prs.base_repo_id = projects.id
ORDER BY prs.num_prs DESC
LIMIT 20

In [17]:
df

    num_prs  base_repo_id                  name  deleted
0     82846      20170979  everypolitician-data    False
1     69340      70604300    signcla-probe-repo    False
2     55760           789        liferay-portal    False
3     54805      33253535                sauron    False
4     40082       9570147         homebrew-cask    False
5     33504       6866209              homebrew    False
6     31212           202                  gaia    False
7     30909       1803391       snoopys-sandbox    False
8     28820          3777               nixpkgs    False
9     28289      22091370            kubernetes    False
10    28273          1142                  salt    False
11    23473      32902832         homebrew-core    False
12    22997       7301975             patchwork    False
13    21373      30513020           sauron-demo    False
14    20960       3149844                 cmssw    False
15    20836          1334                 rails    False
16    20806       8196280                 spark    False
17    20747          1486               ansible    False
18    20554         17694                  ceph    False
19    20537      11703554          code-dot-org    False

In [0]:
# Fetch the largest 20 projects by number of unqiue commenters
%%bigquery --project cs224w-257119 df
SELECT COUNT(comments.comment_id) as num_comments, COUNT(DISTINCT comments.user_id) as num_commenters, prs.base_repo_id
FROM `ghtorrent-bq.ght_2018_04_01.pull_request_comments` comments
INNER JOIN `ghtorrent-bq.ght_2018_04_01.pull_requests` prs ON prs.id = comments.pull_request_id
GROUP BY prs.base_repo_id
ORDER BY num_commenters DESC
LIMIT 20

In [5]:
df

    num_comments  num_commenters  base_repo_id
0          29263            1575       6866209
1          25484            1467          1334
2          10883            1453       4230805
3         132861            1254      22091370
4         130700            1249       8196280
5          41602            1183           634
6          11346            1106       9988540
7          21462            1025          1486
8          16478            1020      32902832
9          39339             984      10313229
10         42367             979      20078281
11         25311             956          3777
12         28964             895          1226
13         37223             742      10998645
14         43209             730          5219
15          8030             726       1992097
16         10036             647      17991525
17         31100             626      34896252
18         13447             625       3905191
19          6510             614       9570147